### ISSUE TITLE
css冲突问题

### ISSUE THREAD

**Issue by DDDDDDDOU** [Team-Salt/Front-React#46]
# 不要在某个css文件里面对全局标签定义样式
比如PdfReaderView.css中的这个定义
```css
input {
    display: inline-block;
    width: 50px;
    text-align: center;    //这一个会导致输入框从中间输入
    margin-right: 10px;
    height: 24px;
}
```

如果需要的话放在index.css里面

# 对于小范围的全局样式也可以在index里面加一个类，然后需要应用的标签加上这个类名就行

# 在单独的css文件里定义的样式，在其他文件里即使不import也会被应用。（这好像是React的问题）所以尽可能使用当前文件特定的类名，避免使用大众化的如PaperDetail、InputDiv这种

# 每次合并完大家检查一下是否有问题
